/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-09 00:43:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.bean.Book;
import model.bean.Account;

public final class QLSach_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/admin/../comp/Footer.jsp", Long.valueOf(1552871050899L));
    _jspx_dependants.put("/admin/../comp/Header.jsp", Long.valueOf(1657324790277L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.Account");
    _jspx_imports_classes.add("model.bean.Book");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<title>Admin Quản Lý</title>\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"../image/LOGO.ico\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../lib/css/stylesheet.css\"\r\n");
      out.write("	data-minify=\"1\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../lib/css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../lib/css/sheet.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../lib/css/styleView.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"../lib/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../lib/js/Cookies.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../lib/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function saveBook() {\r\n");
      out.write("		var action = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${action}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		if (action == \"add\" || action == \"modify\") {\r\n");
      out.write("			//Set up value to save\r\n");
      out.write("			var id, name, gia, theLoai, nxb, tacGia, moTa, duongDan;\r\n");
      out.write("\r\n");
      out.write("			if (action == \"modify\")\r\n");
      out.write("				id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("			name = $(\"#name\").val();\r\n");
      out.write("			gia = $(\"#price\").val();\r\n");
      out.write("			theLoai = $(\"#category\").val();\r\n");
      out.write("			nxb = $(\"#NXB\").val();\r\n");
      out.write("			tacGia = $(\"#author\").val();\r\n");
      out.write("			moTa = $(\"#figure\").val();\r\n");
      out.write("			duongDan = document.cookie.split(\"=\")[1];\r\n");
      out.write("\r\n");
      out.write("			if (action == \"add\") {\r\n");
      out.write("				$.post(\"../Manager/Sach?action=add\", {\r\n");
      out.write("					name : name,\r\n");
      out.write("					gia : gia,\r\n");
      out.write("					theLoai : theLoai,\r\n");
      out.write("					nxb : nxb,\r\n");
      out.write("					tacGia : tacGia,\r\n");
      out.write("					moTa : moTa,\r\n");
      out.write("					duongDan : duongDan\r\n");
      out.write("				}, function(data, status) {\r\n");
      out.write("					deleteCookie(\"img\");\r\n");
      out.write("					window.location.reload();\r\n");
      out.write("					$(\"#image\").attr(\"src\", \"../lib/image/none.png\");\r\n");
      out.write("					$(\"input, textarea\").val(\"\");\r\n");
      out.write("\r\n");
      out.write("				});\r\n");
      out.write("			} else {\r\n");
      out.write("				var imageAction = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imageAction}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("				if (imageAction == \"add\") {\r\n");
      out.write("					$.post(\"../Manager/Sach?action=modify\", {\r\n");
      out.write("						id : id,\r\n");
      out.write("						name : name,\r\n");
      out.write("						gia : gia,\r\n");
      out.write("						theLoai : theLoai,\r\n");
      out.write("						nxb : nxb,\r\n");
      out.write("						tacGia : tacGia,\r\n");
      out.write("						moTa : moTa,\r\n");
      out.write("						imageAction : imageAction,\r\n");
      out.write("						duongDan : duongDan\r\n");
      out.write("					}, function(data, status) {\r\n");
      out.write("						deleteCookie(\"img\");\r\n");
      out.write("						window.location.href = \"KhoSach\";\r\n");
      out.write("					});\r\n");
      out.write("				} else {\r\n");
      out.write("					if (duongDan == null) {\r\n");
      out.write("						duongDan = $(\"#image\").attr(\"src\");\r\n");
      out.write("						duongDan = duongDan.substring(\r\n");
      out.write("								duongDan.lastIndexOf(\"/\") + 1, duongDan.length);\r\n");
      out.write("					}\r\n");
      out.write("\r\n");
      out.write("					$.post(\"../Manager/Sach?action=modify\", {\r\n");
      out.write("						id : id,\r\n");
      out.write("						name : name,\r\n");
      out.write("						gia : gia,\r\n");
      out.write("						theLoai : theLoai,\r\n");
      out.write("						nxb : nxb,\r\n");
      out.write("						tacGia : tacGia,\r\n");
      out.write("						moTa : moTa,\r\n");
      out.write("						imageAction : imageAction,\r\n");
      out.write("						duongDan : duongDan,\r\n");
      out.write("						maAnh : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${maAnh}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\r\n");
      out.write("					}, function(data, status) {\r\n");
      out.write("						deleteCookie(\"img\");\r\n");
      out.write("						window.location.href = \"KhoSach\";\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function resetInput() {\r\n");
      out.write("		document.getElementById(\"name\").value = \"\";\r\n");
      out.write("		document.getElementById(\"price\").value = \"\";\r\n");
      out.write("		document.getElementById(\"category\").value = \"\";\r\n");
      out.write("		document.getElementById(\"NXB\").value = \"\";\r\n");
      out.write("		document.getElementById(\"author\").value = \"\";\r\n");
      out.write("		document.getElementById(\"figure\").value = \"\";\r\n");
      out.write("		document.getElementById(\"image\").src = \"\";\r\n");
      out.write("		document.getElementById(\"inputImage\").value = \"\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	window\r\n");
      out.write("			.addEventListener(\r\n");
      out.write("					\"load\",\r\n");
      out.write("					function() {\r\n");
      out.write("						document.getElementById(\"inputImage\").onchange = function(\r\n");
      out.write("								event) {\r\n");
      out.write("							var tmppath = URL\r\n");
      out.write("									.createObjectURL(event.target.files[0]);\r\n");
      out.write("							$(\"#image\").attr(\"src\",\r\n");
      out.write("									URL.createObjectURL(event.target.files[0]));\r\n");
      out.write("							setCookie(\"img\", event.target.files[0].name);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"common-home\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Phần header cho trang Web -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<!-- Thanh topbar -->\r\n");
      out.write("		<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Thanh tiêu để trên cùng dành cho màn hình trung bình và hẹp -->\r\n");
      out.write("			<div class=\"topbar\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						");

							boolean isAdmin = false;
							if (request.getRequestURI().indexOf("Manager") != -1)
								isAdmin = true;
						
      out.write("\r\n");
      out.write("						<div class=\"col-lg-1 col-md-1 col-sm-1 col-xs-1 col-ms-1\">\r\n");
      out.write("							");

								if (isAdmin)
									out.println(
											"<a href=\"../Home\"><img alt=\"logo\" src=\"../image/logo.jpg\" style=\"width: 55px; margin-left: -20px;\"></img></a>");
								else
									out.println(
											"<a href=\"Home\"><img alt=\"logo\" src=\"image/logo.jpg\" style=\"width: 55px; margin-left: -20px;\"></img></a>");
							
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-4 col-md-4 col-sm-4 col-xs-4 col-ms-4\">\r\n");
      out.write("							");

								if (isAdmin)
									out.println(
											"<form action=\"../Search\" method=\"GET\" class=\"search-bar clearfix\" id=\"search-textbox\">");
								else
									out.println(
											"<form action=\"Search\" method=\"GET\" class=\"search-bar clearfix\" id=\"search-textbox\">");
							
      out.write("\r\n");
      out.write("							<input name=\"strSearch\" type=\"text\" id=\"Search\"\r\n");
      out.write("								placeholder=\"Nhập tên sách...\"\r\n");
      out.write("								style=\"border: 1px solid #dcdcdc; border-radius: 0;\"></input> <span><button\r\n");
      out.write("									type=\"submit\">\r\n");
      out.write("									<i class=\"fa fa-search\" style=\"margin-top: 0\"></i>\r\n");
      out.write("								</button></span>\r\n");
      out.write("							");

								out.println("</form>");
							
      out.write("\r\n");
      out.write("							<div id=\"zoom-btn\">\r\n");
      out.write("								<i class=\"fa fa-search\"></i>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-lg-6 col-md-6 col-sm-6 col-xs-6 col-ms-6\">\r\n");
      out.write("							<div class=\"icon-bar horizontal\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"i-right dropdown\">\r\n");
      out.write("											<i class=\"fa fa-user\"></i>\r\n");
      out.write("											<div class=\"right-dropdown-content\">\r\n");
      out.write("												");

													HttpSession ses = request.getSession();
													Account user = (Account) ses.getAttribute("User");
													if (user == null) {
														out.println("<ul>");
														out.println("<li><a href=\"login\">Đăng nhập</a>");
														out.println("<li><a class=\"signup-window\" href=\"#signup-box\">Đăng ký tài khoản</a>");
														out.println("</ul>");
													} else {
														out.println("<ul>");
														if (isAdmin)
															out.println("<li><a href=\"BangTin\">Trang quản lý</a>");
														out.println("<li><a href=\"ViewInfo\">Thông tin tài khoản</a>");
														out.println("<li><a href=\"logout\">Đăng xuất</a>");
														out.println("</ul>");
													}
												
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("									<li>\r\n");
      out.write("										<div class=\"top-cart cart-icon\">\r\n");
      out.write("											<a href=\"ViewCart\"><i class=\"fa fa-briefcase\"\r\n");
      out.write("												style=\"color: #92929D\"></i></a>\r\n");
      out.write("											<div class=\"cart-count\">\r\n");
      out.write("												");

													int count = 0;
													Cookie[] arg_Cookies = request.getCookies();
													if (arg_Cookies != null) {
														for (int i = 0; i < arg_Cookies.length; i++) {
															Cookie cookie = arg_Cookies[i];
															if (arg_Cookies[i].getName().equalsIgnoreCase("countBook")) {
																count = Integer.parseInt(cookie.getValue());
															}
														}
													}
													out.println("<span id=\"number\">" + count + "</span>");
												
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- Thanh menu -->\r\n");
      out.write("			<nav style=\"background: #F7F7F7\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<!-- Menu -->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-lg-12 col-md-12 col-sm-12 col-ms-12\">\r\n");
      out.write("							<div class=\"navbar\" style=\"border: none;\">\r\n");
      out.write("								<ul class=\"nav nav-left\">\r\n");
      out.write("									\r\n");
      out.write("									");

										if (!isAdmin) {
											out.println("<li class=\"nav-item nav-item-lv1 active\"><a class=\"nav-link\" href=\"Home\">Trang chủ</a></li>");
											out.println(
													"<li class=\"nav-item nav-item-lv1\"><a class=\"nav-link\" href=\"Categories?danhMuc=yeuthich\">Sách yêu thích</a></li>");
											out.println(
													"<li class=\"nav-item nav-item-lv1\"><a class=\"nav-link\" href=\"Categories?danhMuc=banchay\">Sách bán chạy</a></li>");
										} else {
											out.println("<li class=\"nav-item nav-item-lv1 active\"><a class=\"nav-link\" href=\"../Home\">Trang chủ</a></li>");
											out.println(
													"<li class=\"nav-item nav-item-lv1\"><a class=\"nav-link\" href=\"BangTin\">Bảng Tin</a></li>");
											out.println(
													"<li class=\"nav-item nav-item-lv1\"><a class=\"nav-link\" href=\"DonHang\">Đơn hàng</a></li>");
											out.println(
													"<li class=\"nav-item nav-item-lv1\"><a class=\"nav-link\" href=\"KhachHang\">Khách hàng</a></li>");
											out.println(
													"<li class=\"nav-item nav-item-lv1\"><a class=\"nav-link\" href=\"KhoSach\">Kho sách</a></li>");
										}
									
      out.write("\r\n");
      out.write("								</ul>\r\n");
      out.write("								<div class=\"nav nav-toggle\">\r\n");
      out.write("									<button id=\"btn-toggle\">\r\n");
      out.write("										<i class=\"fa fa-align-justify\"></i>\r\n");
      out.write("									</button>\r\n");
      out.write("									<div class=\"toggle-content\">\r\n");
      out.write("										");

											if (!isAdmin) {
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println("onclick=\"gotoPage('Home')\"><a href=\"Home\">Trang chủ</a></span> ");
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println(
														"onclick=\"gotoPage('Categories?danhMuc=yeuthich')\"><a href=\"Categories?danhMuc=yeuthich\">Sách yêu thích</a></span>");
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println(
														"onclick=\"gotoPage('Categories?danhMuc=banchay')\"><a href=\"Categories?danhMuc=banchay\">Sách bán chạy</a></span>");
											} else {
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println("onclick=\"gotoPage('../Home')\"><a href=\"./Home\">Trang chủ</a></span> ");
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println("onclick=\"gotoPage('BangTin')\"><a href=\"BangTin\">Bảng tin</a></span>");
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println("onclick=\"gotoPage('DonHang')\"><a href=\"DonHang\">Đơn hàng</a></span>");
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println("onclick=\"gotoPage('KhachHang')\"><a href=\"KhachHang\">Khách hàng</a></span>");
												out.print("<span class=\"toggle-item\" style=\"cursor: pointer;\"");
												out.println("onclick=\"gotoPage('KhoSach')\"><a href=\"KhoSach\">Kho sách</a></span>");
											}
										
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"signup-container\" id=\"signup-box\">\r\n");
      out.write("		<h1>Đăng ký</h1>\r\n");
      out.write("		<span class=\"img-close\"><i id=\"size-icon\" class=\"fa fa-close\"></i></span>\r\n");
      out.write("		<form class=\"signup-content\">\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"NameSignUp\">Tên đăng nhập</label>\r\n");
      out.write("				<input type=\"text\" name=\"NameSignUp\" value=\"\"\r\n");
      out.write("					placeholder=\"User name\" maxlength=\"10\" autocomplete=\"off\"\r\n");
      out.write("					id=\"NameSignUp\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"UserSignUp\">Tên người dùng</label>\r\n");
      out.write("				<input type=\"text\" name=\"UserSignUp\" value=\"\"\r\n");
      out.write("					placeholder=\"Your name\" maxlength=\"50\" autocomplete=\"off\"\r\n");
      out.write("					id=\"UserSignUp\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"Sex\">Giới tính</label> <select\r\n");
      out.write("					class=\"form-control\" name=\"Sex\" id=\"Sex\">\r\n");
      out.write("					<option>Nam</option>\r\n");
      out.write("					<option>Nữ</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"BirthDate\">Ngày sinh</label> <input\r\n");
      out.write("					id=\"typedate\" type=\"date\" name=\"Date\" value=\"\" id=\"BirthDate\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"Address\">Địa chỉ</label> <input\r\n");
      out.write("					type=\"text\" name=\"Address\" value=\"\" placeholder=\"Address\"\r\n");
      out.write("					maxlength=\"255\" id=\"Address\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"Email\">Email</label> <input\r\n");
      out.write("					type=\"email\"  name=\"Email\" value=\"\" placeholder=\"name@example.com\"\r\n");
      out.write("					maxlength=\"50\" id=\"Email\" required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"PhoneNumber\">Số điện thoại\r\n");
      out.write("					liên hệ</label> <input type=\"number\" name=\"PhoneNumber\" value=\"\"\r\n");
      out.write("					placeholder=\" Your phone number\" maxlength=\"10\" id=\"PhoneNumber\"\r\n");
      out.write("					required>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"Password\">Mật khẩu đăng\r\n");
      out.write("					nhập</label> <input type=\"password\" name=\"Password\" value=\"\"\r\n");
      out.write("					placeholder=\" Your password\" id=\"Password\" maxlength=\"50\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"form-group\">\r\n");
      out.write("				<label class=\"control-label\" for=\"Confirmpassword\">Xác nhận\r\n");
      out.write("					mật khẩu</label> <input type=\"password\" name=\"Confirmassword\" value=\"\"\r\n");
      out.write("					placeholder=\" Confirm your password\" id=\"Confirmpassword\"\r\n");
      out.write("					maxlength=\"50\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div style=\"position: relative; width: 100%; text-align: center\">\r\n");
      out.write("				<button class=\"button submit-button\" onclick=\"dangkytk()\">Đăng\r\n");
      out.write("					ký</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			</br>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("			$(document).ready(function(){\r\n");
      out.write("				\r\n");
      out.write("				var child=$(\".nav.nav-left\").children();\r\n");
      out.write("				$(child).removeClass(\"active\");\r\n");
      out.write("				var url = location.href;\r\n");
      out.write("				\r\n");
      out.write("				if (url.indexOf(\"Categories\") != -1){\r\n");
      out.write("					if (url.indexOf(\"Categories?danhMuc=yeuthich\") != -1) child.eq(1).addClass(\"active\");\r\n");
      out.write("					else if (url.indexOf(\"Categories?danhMuc=banchay\") != -1) child.eq(2).addClass(\"active\");\r\n");
      out.write("				} else if (url.indexOf(\"Manager\") == -1) child.eq(0).addClass(\"active\");\r\n");
      out.write("				if (url.indexOf(\"Manager\") != -1){\r\n");
      out.write("					if (url.indexOf(\"BangTin\") != -1) child.eq(1).addClass(\"active\");\r\n");
      out.write("					else if (url.indexOf(\"DonHang\") != -1) child.eq(2).addClass(\"active\");\r\n");
      out.write("					else if (url.indexOf(\"KhachHang\") != -1) child.eq(3).addClass(\"active\");\r\n");
      out.write("					else if (url.indexOf(\"KhoSach\") != -1 || url.indexOf(\"Sach\") != -1) child.eq(4).addClass(\"active\");\r\n");
      out.write("				} else child.eq(0).addClass(\"active\");\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				$(\"#signup-box\").click(function(){\r\n");
      out.write("					var height = $(\"#btn-toggle\").next().css(\"height\");\r\n");
      out.write("					if (height == '0px'){\r\n");
      out.write("						$(\"#btn-toggle\").next().animate({\"height\":\"40%\"}, 450);\r\n");
      out.write("					} else {\r\n");
      out.write("						$(\"#btn-toggle\").next().animate({\"height\":\"0px\"}, 450);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("			$(document).on(\"mouseover\", \".dropdown\", function(){\r\n");
      out.write("				$(\".dropdown .right-dropdown-content\").css({\"display\":\"block\"});\r\n");
      out.write("				$(\".dropdown .right-dropdown-content\").animate({\"opacity\":\"1.0\"}, 100);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			$(document).on(\"mouseleave\", \".dropdown, .right-dropdown-content\", function(){\r\n");
      out.write("				$(\".dropdown .right-dropdown-content\").animate({\"opacity\":\"0\"}, 100, function(){\r\n");
      out.write("					$(\".dropdown .right-dropdown-content\").css({\"display\":\"none\"});\r\n");
      out.write("				});\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			function dangkytk(){\r\n");
      out.write("				var TenDangNhap,TenNguoiDung,GioiTinh,NgaySinh,DiaChi,Email,SDT,MatKhau,XNMatKhau;\r\n");
      out.write("				TenDangNhap= $('#NameSignUp').val();\r\n");
      out.write("				MatKhau=$('#Password').val();\r\n");
      out.write("				TenNguoiDung=$('#UserSignUp').val();\r\n");
      out.write("				GioiTinh=$('#Sex').val();\r\n");
      out.write("				NgaySinh=$('#typedate').val(); \r\n");
      out.write("				DiaChi=$('#Address').val();\r\n");
      out.write("				Email=$('#Email').val();\r\n");
      out.write("				SDT=$('#PhoneNumber').val();\r\n");
      out.write("				XNMatKhau=$('#Confirmpassword').val();\r\n");
      out.write("				if(confirmpass(MatKhau,XNMatKhau)==true)\r\n");
      out.write("					{\r\n");
      out.write("						$.post('SignUp',{\r\n");
      out.write("							TenDangNhap:TenDangNhap,\r\n");
      out.write("							TenNguoiDung:TenNguoiDung,\r\n");
      out.write("							GioiTinh:GioiTinh,\r\n");
      out.write("							NgaySinh:NgaySinh,\r\n");
      out.write("							DiaChi:DiaChi,\r\n");
      out.write("							Email:Email,\r\n");
      out.write("							SDT:SDT,\r\n");
      out.write("							MatKhau:MatKhau\r\n");
      out.write("						}, function(){\r\n");
      out.write("							$('.signup-container').fadeOut(100);	\r\n");
      out.write("						});\r\n");
      out.write("					}\r\n");
      out.write("			}\r\n");
      out.write("			function confirmpass(MatKhau,XNMatKhau)\r\n");
      out.write("			{\r\n");
      out.write("				return (MatKhau==XNMatKhau)\r\n");
      out.write("					\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\" id=\"content\">\r\n");
      out.write("		<div class=\"row\" style=\"background-color: #eeeeee;\">\r\n");
      out.write("			<div class=\"col-sm-12\" id=\"main-content\">\r\n");
      out.write("				<div class=\"board\" style=\"padding: 0px !important;\">\r\n");
      out.write("					<!--Button-->\r\n");
      out.write("					<div class=\"col-ms-3 aSM\" style=\"text-align: center;\">\r\n");
      out.write("						<a href=\"\">Hủy</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					");

						Object action = request.getAttribute("action");
						if (action != null) {
							if (action.equals("add")) {
								out.println("<div class=\"col-ms-6 tuade\">Nhập thêm sách</div>");
							} else if (action.equals("modify")) {
								out.println("<div class=\"col-ms-6 tuade\">Cập nhật thông tin sách</div>");
							}
						}
					
      out.write("\r\n");
      out.write("					<div class=\"col-ms-3 aSM\" style=\"text-align: center;\">\r\n");
      out.write("						<div id=\"submit\" onclick=\"saveBook()\"\r\n");
      out.write("							style=\"cursor: pointer; color: blue;\">Chấp nhận</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"board\">\r\n");
      out.write("\r\n");
      out.write("					<!--Khung thông tin-->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-sm-5 col-xs-12\">\r\n");
      out.write("							");

								Book book = null;
								if (action != null) {
									if (action.equals("modify")) {
										book = (Book) request.getAttribute("book");

										out.println("<div class=\"NhapSachIMG\">");
										out.println("<img id=\"image\" src=\"../lib/image/" + book.getImages().getDuongDan() + "\"></img>");
										out.println(
												"<input type=\"file\" accept=\"image/* \" style=\"width: 100%;\" id=\"inputImage\"></div>");
									} else if (action.equals("add")) {
										book = new Book();

										out.println("<div class=\"NhapSachIMG\">");
										out.println("<img id=\"image\" src=\"../lib/image/none.png\"></img>");
										out.println(
												"<input type=\"file\" accept=\"image/* \" style=\"width: 100%;\" id=\"inputImage\"></div>");
									}
								}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						");

							if (book != null) {
								out.println("<div class=\"col-sm-7 col-xs-12\">");
								out.println("<div class=\"NhapSachINFO\">");

								//Input name
								out.println("<div class=\"fixLB\">");
								out.println("<i class=\"fa fa-book\" aria-hidden=\"true\"></i>");
								out.println("<label for=\"name\">Tên Sách</label>");
								out.println(
										"<input type=\"text\" name=\"name\" placeholder=\"VD: Sherlock Holmes\" id=\"name\" value=\""
												+ book.getTenSach() + "\"></div>");
								out.println("<br>");

								//Input price
								out.println("<div class=\"fixLB\">");
								out.println("<i class=\"fa fa-book\" aria-hidden=\"true\"></i>");
								out.println("<label for=\"name\">Giá Sách</label>");
								if (book.getGiaBan() > 0) {
									out.println("<input type=\"text\" name=\"price\" placeholder=\"VD: 220000\" id=\"price\" value=\""
											+ book.getGiaBan() + "\"></div>");
								} else {
									out.println("<input type=\"text\" name=\"price\" placeholder=\"VD: 220000\" id=\"price\"></div>");
								}
								out.println("<br>");

								//Input nxb
								out.println("<div class=\"fixLB\">");
								out.println("<i class=\"fa fa-book\" aria-hidden=\"true\"></i>");
								out.println("<label for=\"name\">Nhà Xuất Bản</label>");
								out.println(
										"<input type=\"text\" name=\"NXB\" placeholder=\"VD: Nhà xuất bản Văn Học\" id=\"NXB\" value=\""
												+ book.getNXB() + "\"></div>");
								out.println("<br>");

								//Input category
								out.println("<div class=\"fixLB\">");
								out.println("<i class=\"fa fa-book\" aria-hidden=\"true\"></i>");
								out.println("<label for=\"name\">Thể loại</label>");
								out.println(
										"<input type=\"text\" name=\"category\" placeholder=\"VD: Sherlock Holmes\" id=\"category\" value=\""
												+ book.getTheLoai() + "\"></div>");
								out.println("<br>");

								//Input author
								out.println("<div class=\"fixLB\">");
								out.println("<i class=\"fa fa-book\" aria-hidden=\"true\"></i>");
								out.println("<label for=\"name\">Tác giả</label>");
								out.println(
										"<input type=\"text\" name=\"author\" placeholder=\"VD: Sherlock Holmes\" id=\"author\" value=\""
												+ book.getTacGia() + "\"></div>");

								out.println("</div></div>");

								//Input figure
								out.println("<div class=\"col-ms-12\">");
								out.println("<div class=\"figureNhapSach\">");
								out.println("<i class=\"fa fa-book\" aria-hidden=\"true\"></i>");
								out.println("<label for=\"name\">Mô tả</label>");
								out.println("<textarea placeholder=\"Mô tả\" id=\"figure\">" + book.getMoTa() + "</textarea></div>");

								out.println("</div></div>");
							}
						
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- <div class=\"row\">\r\n");
      out.write("						<div class=\"col-ms-3\">\r\n");
      out.write("							<div class=\"button-modify\">\r\n");
      out.write("								<div class=\"button-rect forest\">\r\n");
      out.write("									<i class=\"fa fa-money\"></i>\r\n");
      out.write("									<span class=\"content-inner\">Hủy</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-ms-6\"></div>\r\n");
      out.write("						<div class=\"col-ms-3\">\r\n");
      out.write("							<div class=\"button-modify\">\r\n");
      out.write("								<div class=\"button-rect cool\">\r\n");
      out.write("									<i class=\"fa fa-money\"></i>\r\n");
      out.write("									<span class=\"content-inner\">Chấp nhận</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write(" -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Phần footer cho trang Web -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer class=\"footer\">\r\n");
      out.write("		<div class=\"content\">\r\n");
      out.write("			<div class=\"site-footer\">\r\n");
      out.write("				<div class=\"copyright clearfix\">\r\n");
      out.write("					<div class=\"container\">\r\n");
      out.write("						<div class=\"inner clearfix\">\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-md-12 text-center text-lg-left\">\r\n");
      out.write("									<div class=\"col-md-12 text-center text-lg-left\">\r\n");
      out.write("										<div class=\"col-sm-12 col-md-12 col-xs-12 footer-static-title\">\r\n");
      out.write("											<div class=\"col-sm-4 col-md-4\" style=\"padding-right: 10px;\">\r\n");
      out.write("												<div class=\"col-sm-12 col-md-12 col-xs-12 icon-footer\"\r\n");
      out.write("													style=\"margin-bottom: 10px;\">\r\n");
      out.write("													");
 
														if (request.getRequestURI().indexOf("Manager") == -1)
															out.println("<img alt=\"logo\" src=\"image/logo.jpg\" style=\"width: 75px; margin-left: 8px;\">");
														else
															out.println("<img alt=\"logo\" src=\"../image/logo.jpg\" style=\"width: 75px; margin-left: 8px;\">");
													
      out.write("\r\n");
      out.write("													\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-sm-12 col-md-12 col-xs-12 address-footer\"\r\n");
      out.write("													style=\"font-size: 13px; float: left;\">Số 1, đường Võ\r\n");
      out.write("													Văn Ngân, phường Linh Chiểu, quận Thủ Đức, Tp.Hcm</div>\r\n");
      out.write("												<div class=\"col-sm-12 col-md-12 col-xs-12 address-footer\"\r\n");
      out.write("													style=\"font-size: 13px; padding-top: 2px;\">YeuSach.com\r\n");
      out.write("													nhận đặt hàng trực tuyến và giao hàng tận nơi. KHÔNG hỗ trợ\r\n");
      out.write("													đặt mua và nhận hàng trực tiếp tại văn phòng cũng như tất\r\n");
      out.write("													cả Hệ Thống Yêu sách Bookstore trên toàn quốc.</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-4 col-md-4 col-xs-12\"\r\n");
      out.write("												style=\"padding: 0px;\">\r\n");
      out.write("												<div class=\"col-sm-12 col-md-12 col-xs-12\" align=\"center\"\r\n");
      out.write("													style=\"font-size: 14.5px; margin-bottom: 20px; margin-top: 10px; padding: 0px;\">\r\n");
      out.write("													<a target=\"_blank\"\r\n");
      out.write("														href=\"javascript:void(0)\"\r\n");
      out.write("														title=\"Facebook\"> <img alt=\"Facebook\"\r\n");
      out.write("														src=\"https://www.fahasa.com/skin/frontend/ma_vanese/fahasa/images/footer/Facebook-on.png\">\r\n");
      out.write("													</a> <a target=\"_blank\"\r\n");
      out.write("														href=\"javascript:void(0)\"\r\n");
      out.write("														title=\"Instagram\"> <img alt=\"Instagram\"\r\n");
      out.write("														src=\"https://www.fahasa.com/skin/frontend/ma_vanese/fahasa/images//footer/Insta-on.png\">\r\n");
      out.write("													</a> <a target=\"_blank\" href=\"\" title=\"Youtube\"> <img\r\n");
      out.write("														alt=\"Youtube\"\r\n");
      out.write("														src=\"https://www.fahasa.com/skin/frontend/ma_vanese/fahasa/images//footer/Youtube-on.png\">\r\n");
      out.write("													</a> <a target=\"_blank\" href=\"javascript:void(0)\"\r\n");
      out.write("														title=\"Twitter\"> <img alt=\"Twitter\"\r\n");
      out.write("														src=\"https://www.fahasa.com/skin/frontend/ma_vanese/fahasa/images//footer/twitter-on.png\">\r\n");
      out.write("													</a>\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-sm-12 col-md-12 col-xs-12\"\r\n");
      out.write("													style=\"font-size: 14.5px\">\r\n");
      out.write("													<div class=\"col-sm-6 col-md-6 col-xs-6\"\r\n");
      out.write("														style=\"text-align: right;\">\r\n");
      out.write("														<a\r\n");
      out.write("															href=\"javascript:void(0)\">\r\n");
      out.write("															<img alt=\"Bookstore.COM\"\r\n");
      out.write("															src=\"https://www.fahasa.com/media/wysiwyg/Logo-NCC/android.png\"\r\n");
      out.write("															style=\"max-width: 110px;\">\r\n");
      out.write("														</a>\r\n");
      out.write("													</div>\r\n");
      out.write("													<div class=\"col-sm-6 col-md-6 col-xs-6\">\r\n");
      out.write("														<a href=\"javascript:void(0)\"> <img\r\n");
      out.write("															alt=\"Bookstore.COM\"\r\n");
      out.write("															src=\"https://www.fahasa.com/media/wysiwyg/Logo-NCC/appstore.png\"\r\n");
      out.write("															style=\"max-width: 110px;\">\r\n");
      out.write("														</a>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-sm-4 col-md-4 \" style=\"padding: 5px;\">\r\n");
      out.write("												<div class=\"footer-static-title\">\r\n");
      out.write("													<h3>Liên hệ</h3>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"footer-static-content\">\r\n");
      out.write("													<ul>\r\n");
      out.write("														<li class=\"first\"><em class=\"fa fa-map-marker\">&nbsp;</em><span>\r\n");
      out.write("															Địa Chỉ:</span> 01 Võ Văn Ngân, Linh Trung, Thủ Đức, TP. HCM</li>\r\n");
      out.write("														<li><em class=\"fa fa-envelope\">&nbsp;</em><span>\r\n");
      out.write("														Email:</span> Yeusach@YeusachBookstore.com</li>\r\n");
      out.write("														<li class=\"last\"><em class=\"fa fa-phone\">&nbsp;</em><span>\r\n");
      out.write("															Phone:</span> 190055555</li>\r\n");
      out.write("													</ul>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(document).ready(function() {\r\n");
      out.write("			$('a.signup-window').click(function() {\r\n");
      out.write("				//lấy giá trị thuộc tính href - chính là phần tử \"#signup-box\"\r\n");
      out.write("				var signupBox = $(this).attr('href');\r\n");
      out.write("				//cho hiện hộp đăng nhập trong 300ms\r\n");
      out.write("				$(signupBox).fadeIn(400);\r\n");
      out.write("				// thêm phần tử id=\"over\" vào sau body\r\n");
      out.write("				$('body').append('<div id=\"over\">');\r\n");
      out.write("				$('#over').fadeIn(400);\r\n");
      out.write("				return false;\r\n");
      out.write("			});\r\n");
      out.write("			// khi click đóng hộp thoại\r\n");
      out.write("			$(document).on('click', \"span.img-close, #over\", function() {\r\n");
      out.write("				$('#over, .signup-container').fadeOut(200, function() {\r\n");
      out.write("					$('#over').remove();\r\n");
      out.write("				});\r\n");
      out.write("				return false;\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function addCart() {\r\n");
      out.write("			var url = 'ViewCart?action=add'\r\n");
      out.write("			var name = $('#username').val();\r\n");
      out.write("			var address = $('#address').val();\r\n");
      out.write("			var phone = $('#phone').val();\r\n");
      out.write("\r\n");
      out.write("			$.post(url, {\r\n");
      out.write("				name : name,\r\n");
      out.write("				address : address,\r\n");
      out.write("				phone : phone\r\n");
      out.write("			}, function() {\r\n");
      out.write("				alert('Đặt hàng thành công!');\r\n");
      out.write("\r\n");
      out.write("				var url = location.href;\r\n");
      out.write("				deleteAllCookie();\r\n");
      out.write("				location.href = url.substring(0, url.lastIndexOf('/'));\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function buyNow(id, soluong) {\r\n");
      out.write("			addBookToCart(id, soluong);\r\n");
      out.write("			showPayDialog();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function showPayDialog() {\r\n");
      out.write("			//cho hiện hộp đăng nhập trong 300ms\r\n");
      out.write("			$('.dialog').fadeIn(300);\r\n");
      out.write("\r\n");
      out.write("			// thêm phần tử id=\"over\" vào sau body\r\n");
      out.write("			$('body').append('<div id=\"over\">');\r\n");
      out.write("			$('#over').fadeIn(300);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function addBookToCart(id, soluong) {\r\n");
      out.write("			var count = getCookie(\"countBook\");\r\n");
      out.write("			if (count.length == 0)\r\n");
      out.write("				count = 1;\r\n");
      out.write("			else\r\n");
      out.write("				count++;\r\n");
      out.write("\r\n");
      out.write("			setCookie(\"book\" + count, \"id:\" + id + \"-count:\" + soluong); //Thêm sách đã mua vào cookie\r\n");
      out.write("			setCookie(\"countBook\", count);\r\n");
      out.write("			$(\".cart-count\").load(document.URL + \" #number\");\r\n");
      out.write("			$(\"#countInput\").load(document.URL + \" #count\");\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//Goto url\r\n");
      out.write("		function gotoPage(url) {\r\n");
      out.write("			document.location.href = url;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//Use in ViewBook.jsp\r\n");
      out.write("		function getNumberBuy() {\r\n");
      out.write("			var inputNumber = document.getElementById(\"count\");\r\n");
      out.write("			return inputNumber.value;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//Use in ViewBook.jsp\r\n");
      out.write("		function zoomImage(mini_image, zoom_image, name) {\r\n");
      out.write("			var url = \"url\" + \"(lib/image/\" + name + \")\";\r\n");
      out.write("			var image = document.getElementById(zoom_image);\r\n");
      out.write("			image.style.content = url; //Thay đổi đường dẫn của zoom-image \r\n");
      out.write("\r\n");
      out.write("			/*Thay đổi active image*/\r\n");
      out.write("			var oldActiveImage = document\r\n");
      out.write("					.getElementsByClassName(\"mini-image active\")[0];\r\n");
      out.write("			oldActiveImage.className = \"mini-image\"; //Xóa trạng thái active hình hiện tại\r\n");
      out.write("			mouseOutImage(oldActiveImage);//Chỉnh sửa thuộc tính cho hình\r\n");
      out.write("			mini_image.className = \"mini-image active\"; //Kích hoạt trạng thía active mới\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//Use in ViewBook.jsp\r\n");
      out.write("		function mouseHoverImage(img) {\r\n");
      out.write("			if (img.className == \"mini-image\") {\r\n");
      out.write("				img.style.opacity = 1.0;\r\n");
      out.write("				img.children[0].border = \"1px solid gray\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//Use in ViewBook.jsp\r\n");
      out.write("		function mouseOutImage(img) {\r\n");
      out.write("			if (img.className == \"mini-image\") {\r\n");
      out.write("				img.style.opacity = 0.75;\r\n");
      out.write("				img.children[0].border = \"none\";\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		//\r\n");
      out.write("		function sendSearch() {\r\n");
      out.write("			var temp = document.getElementById(\"Search\").value;\r\n");
      out.write("			window.location.href = \"Search?strSearch=\" + temp;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
